### ISSUE TITLE
Install ssolverutils?

### ISSUE THREAD

**Issue by taktoa** [rlancaste/stellarsolver#124]
It'd be nice if the CMakeLists.txt installed ssolverutils. I'm working on Rust bindings to stellarsolver and it'd be easier to write a demo app if they were available.

**Comment by rlancaste** [comment]
Hi there,

So StellarSolver is now used extensively by KStars and will hopefully be used by other astronomy programs in the future.  The tester program, the demos, the batch solver, and the tests are all things I have been playing around with to try to develop other things based off my stellarsolver library.  I developed the ssolverutils library to help me develop those apps because I found that I was copying the same code over and over from one program I wrote to the other.  At the moment, while the batch solver and the tester program work pretty much the way I want, I am planning to do a photometry program next.  I have had to keep changing the ssolverutils library as I have made these programs.  I'm not sure it is ready to be released like stellarsolver has been.  But of course you can release a library and then change it later and it does work pretty well with those programs.  So I might be ok with it.

That being said, the CMakeLists does in fact build and install ssolverutils if you build the programs that use it.  It is an optional item when you run cmake.  Are you saying you might like another option to build and install ssolverutils without installing those other programs?  I wouldn't want to make it build and install ssolverutils by default because most users at least for now wouldn't need that library too.

Your thoughts?

Thanks,

Rob

**Comment by taktoa** [comment]
As far as I can tell, it builds but does not install anything except the batch solver and tester program. You need an `install` call to cause cmake to install anything, and there are only `install` calls for those things, not the demos or tests or ssolverutils library.
