### ISSUE TITLE
Forked Stellar Solver and Want to remove QT Core, and Other QT packages

### ISSUE THREAD

**Issue by maguayo6** [rlancaste/stellarsolver#132]
Hi
I've forked the repo and I have a desire to strip out QT, for now QT Core I suppose.

Wondering if there's any starting point to tackle this anyone recommends?

**Comment by rlancaste** [comment]
So the primary purpose for developing StellarSolver was because I wanted to make astrometry.net into a cross platform internal solver that would work on all platforms for KStars and eliminate all the headaches that we had with peoples installations, python settings, and configurations on Windows and Mac computers especially.  KStars is a QT program and it was simplest to make it in QT since that is already cross platform and I was familiar with that from working with kstars.  I am not sure how easy it would be to remove QT, since you would then not be able to rely on QT's features to make this work in a cross platform way.  QT also gave us a bunch of features with threads, object management, and other methods that we would not have if not for QT.  But by all means if you want to try, have fun!

**Comment by maguayo6** [comment]
Thanks for the answer. After doing a deep dive into how QT is used, I understand more of how it's used. My uses for StellarSolver would only be on Linux which is what prompted the removal of QT. 

I'm actually interested in bringing you on as a consultant for StellarSolver for the program I'm using the software on. If you're interested, my LinkedIn is listed in my profile. You can reach out to me there and I can give you more info to see how you feel.

**Comment by rlancaste** [comment]
Thanks!
