### ISSUE TITLE
Readme instructions to download and run stellar solver incorrect?

### ISSUE THREAD

**Issue by warshtub** [rlancaste/stellarsolver#89]
Hi,

I'm having trouble getting StellerSolver even running with MacOS. The readme.md says to get a recent dmg, but there appears to be none for StellarSolver in github... I guess this means KStars?

After using craft to install stellarsolver, there's no description on how to get it started or run it. Does it run from inside KStars or a different app? How do I get the gui I'm seeing in the readme to appear?

Sorry for the newb questions, but I've been hunting on how to do this for the weekend with no luck.

**Comment by rlancaste** [comment]
Hi there no problem,  There is a DMG, it is the 1.8 DMG, there were very few changes from 1.8 - 1.9.   Mainly I just made that release because there was a very critical fix to get it to build again on windows that we had to put in there and we had to release it again to get it to work.  The 1.8 DMG is basically the same as 1.9.  I should probably have built it and added it to the release, maybe I can do that in the next day or two.

StellarSolver was really primarily written to support plate solving internally in KStars.  The GUI version is the Stellar Solver Tester and is definitely useful for plate solving images.  It was primarily developed to test the stellar solver library and get it working well.  You can certainly open many kinds of images and just solve them.  You will need to download index files though to get it to work.

**Comment by rlancaste** [comment]
Ok I just uploaded the binaries.  Sorry about that.
