### ISSUE TITLE
Update input image with solution WCS?

### ISSUE THREAD

**Issue by hjmcc** [rlancaste/stellarsolver#92]
hi everyone, 

Thanks for making this available! It is difficult to set up astrometry.net on mac.

I know that this is not the goal of the project, but it would be very useful if the solution WCS could be applied to the input image for processing data after the fact. I have not seen any way to do this for standalone images in kstars either, or am I missing something? thanks!

**Comment by rlancaste** [comment]
So, in KStars, we mainly treat it as an image acquisition program, so once you plate solve, the WCS info is put into the next capture you take and every subsequent one when they save.  But no, I don't think that there currently is a feature in KStars to plate solve an image and then save that image with WCS information.

As of right now, in the stellarsolvertester program, I don't even have a way set up in the main UI to save images.  You are correct that isn't the goal, mainly it is a program meant to facilitate development of the library, such as to test it, to demonstrate its capabilities and to make improvements.  I do have StellarSolver save images as temporary files so that external programs can solve the images, but not a file - save option.  If I do add a file - save option though, it definitely makes sense to save the WCS in there.

**Comment by hjmcc** [comment]
dear @rlancaste thank you! That is useful. The use case is for images which were acquired which have no solutions. 

If I may,  I have a related question, how can I debug / test  the astrometric solutions in Kstars without capturing images in the sky? We have a small telescope here (not very reliable) and I would like to be able to test previous-taken images to find the optimal configuration inside kstars. Is that possible?

**Comment by rlancaste** [comment]
ok so I have added the ability to save an image with WCS information in it.  But right now, it doesn't save all the fits headers from the original image.  I will probably do more with it later

I am confused by your related question.  If you are trying to capture fake images inside KStars to work on your settings in KStars, you can always use the simulators with settings that will mirror your real world equipment.  Then you can do virtually everything you could do in a real imaging session.  If you are trying to use photos you took before and bring them into KStars to see if the astrometric solutions bring KStars to the right spot, you can use the "load and slew" feature.  If you are trying to use photos you took before inside KStars and pretend that the images are being captured like they would in a real session, you can do that with the simulators' useImageDirectory feature.  Does this help?

**Comment by hjmcc** [comment]
Thank you !
That is very useful.
Cheers
Henry
